import Config

# Auto-run priv/repo/seeds.exs at app boot so `mix phx.server` always has
# demo data. The seed script is idempotent (no-op if a team already exists).
config :ultistats, :seed_on_start, true

# Configure your database
#
# `POSTGRES_PORT` is set per-worktree by `bin/db` (see docker-compose.yml) so
# multiple worktrees can run their own Postgres in parallel without colliding
# on 5432. The port is pinned in .env; load it here so `mix phx.server` picks
# up the right port without needing the shell to source .env first.
postgres_port =
  System.get_env("POSTGRES_PORT") ||
    case File.read(Path.expand("../.env", __DIR__)) do
      {:ok, contents} ->
        Regex.run(~r/^POSTGRES_PORT=(\d+)/m, contents, capture: :all_but_first)
        |> case do
          [port] -> port
          _ -> "5432"
        end

      _ ->
        "5432"
    end

config :ultistats, Ultistats.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: String.to_integer(postgres_port),
  database: "ultistats_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ultistats, UltistatsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LEvHBq40u2DYb/ETDFtVwPPx2dkIeFhMyZUgdeHLqtSZstTLJjZqGVlefaoyoL3Q",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ultistats, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ultistats, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :ultistats, UltistatsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/ultistats_web/router\.ex$",
      ~r"lib/ultistats_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ultistats, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
